### ISSUE TITLE
SNPP/VIIRS references a non-existent meta description

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview-options-eosdis#143]
The following line references a Brightness Temperature markdown file that does not exist:
https://github.com/nasa-gibs/worldview-options-eosdis/blob/master/common/config/wv.json/measurements/Brightness%20Temperature.json#L123

That meta description should be here: 
https://github.com/nasa-gibs/worldview-options-eosdis/tree/master/common/config/metadata/viirs

This is the error in the console:
![missing_viirs_description](https://user-images.githubusercontent.com/17348884/32570045-f22146ee-c490-11e7-91bf-d8aaa7a5dd88.png)

**Comment by minniewong** [comment]
forgot to create that one :(
